Update test-kubernetes-master-nodee2e.yaml

diff --git a/config/jobs/periodic/kubernetes/test-kubernetes-master-nodee2e.yaml b/config/jobs/periodic/kubernetes/test-kubernetes-master-nodee2e.yaml
--- a/config/jobs/periodic/kubernetes/test-kubernetes-master-nodee2e.yaml
+++ b/config/jobs/periodic/kubernetes/test-kubernetes-master-nodee2e.yaml
@@ -41,32 +41,75 @@ periodics:
             - |
               set -o xtrace
 
-              source "./hack/boskos.sh"
+              heartbeat_account(){
+                count=0
+                url="http://${BOSKOS_HOST}/update?name=${BOSKOS_RESOURCE_NAME}&state=busy&owner=${USER}"
+                while [ ${count} -lt 120 ]
+                do
+                  status_code=$(curl -s -o /dev/null -w '%{http_code}' -X POST ${url})
+                  if [[ ${status_code} != 200 ]]; then
+                    echo "Heart beat to resource '${BOSKOS_RESOURCE_NAME}' failed due to invalid response, status code: ${status_code}"
+                    exit 1
+                  fi
+                  count=$(( $count + 1 ))
+                  sleep 60
+                done
+              }
+          
+              if [ -n "${BOSKOS_HOST:-}" ]; then
+                set +o xtrace
+                url="http://${BOSKOS_HOST}/acquire?type=${RESOURCE_TYPE}&state=free&dest=busy&owner=${USER}"
+                output=$(curl -v -X POST ${url})
+                [ $? = 0 ] && status_code=200
+          
+                if [[ ${status_code} == 200 && ${output} =~ "failed" ]]; then
+                  echo "Failed to acquire resource from Boskos of type ${RESOURCE_TYPE}"
+                  exit 1
+                elif [[ ${status_code} == 200 ]]; then
+                  export BOSKOS_RESOURCE_NAME=$(echo ${output} | jq -r '.name')
+                  export BOSKOS_REGION=$(echo ${output} | jq -r '.userdata["region"]')
+                  export BOSKOS_ZONE=$(echo ${output} | jq -r '.userdata["zone"]')
+                  rm -rf output.json
+                else
+                  echo "Failed to acquire resource due to invalid response, status code : ${status_code}"
+                  exit 1
+                fi
+          
+                heartbeat_account >> "$ARTIFACTS/boskos.log" 2>&1 &
+                HEART_BEAT_PID=$(echo $!)
+              fi
+          
+              echo "print variables"
+              echo ${BOSKOS_REGION}
+              echo ${BOSKOS_ZONE}
+              echo ${BOSKOS_RESOURCE_NAME}
+
 
               make install-deployer-tf
 
               CLUSTER_NAME="config2-$(date +%s)"
 
               set +o errexit
-              kubetest2 tf --powervs-image-name CentOS-Stream-10 --powervs-memory 32 \
-                --powervs-region ${BOSKOS_REGION} --powervs-zone ${BOSKOS_ZONE} \
-                --powervs-service-id ${BOSKOS_RESOURCE_ID} --powervs-ssh-key k8s-prow-sshkey \
-                --ssh-private-key /etc/secret-volume/ssh-privatekey \
-                --cluster-name $CLUSTER_NAME \
-                --up --set-kubeconfig=false --auto-approve --retry-on-tf-failure 3 \
-                --build-version $(curl -Ls https://dl.k8s.io/ci/latest.txt) \
-                --break-kubetest-on-upfail true \
-                --playbook k8s-node-remote.yml
+              kubetest2 tf  --target-provider vpc --vpc-node-image-name ibm-ubuntu-22-04-4-minimal-s390x-3 \
+              --vpc-region ${BOSKOS_REGION} --vpc-zone ${BOSKOS_ZONE} \
+              --vpc-name ${BOSKOS_RESOURCE_NAME} \
+              --vpc-resource-group ${BOSKOS_RESOURCE_GROUP} \
+              --vpc-ssh-key k8s-s390x-ssh-key \
+              --vpc-node-profile bz2-4x16 \
+              --cluster-name $CLUSTER_NAME \
+              --up --set-kubeconfig=false --auto-approve --retry-on-tf-failure 3 \
+              --build-version $(curl -Ls https://dl.k8s.io/ci/latest.txt) \
+              --break-kubetest-on-upfail true \
+              --playbook k8s-node-remote.yml
 
               EXTERNAL_IP=`grep -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' $(pwd)/$CLUSTER_NAME/hosts`
 
               # Skipping test related to https://github.com/kubernetes/kubernetes/issues/124791
-              kubetest2 tf --test=exec -- ssh -i /etc/secret-volume/ssh-privatekey root@$EXTERNAL_IP \
+              kubetest2 tf  --target-provider vpc --test=exec -- ssh -i /etc/secret-volume/ssh-privatekey root@$EXTERNAL_IP \
                 "export SKIP='\[Flaky\]|\[Slow\]|\[Serial\]|should.execute.readiness.probe.while.in.preStop' && /make-test-e2e-node.sh"; \
                 rc=$?; scp -r -i /etc/secret-volume/ssh-privatekey root@$EXTERNAL_IP:/tmp/_artifacts $ARTIFACTS
 
-              kubetest2 tf --powervs-region ${BOSKOS_REGION} --powervs-zone ${BOSKOS_ZONE} \
-                --powervs-service-id ${BOSKOS_RESOURCE_ID} \
+              kubetest2 tf --target-provider vpc --vpc-region ${BOSKOS_REGION} --vpc-zone ${BOSKOS_ZONE} \
                 --ignore-cluster-dir true \
                 --cluster-name $CLUSTER_NAME\
                 --down --auto-approve --ignore-destroy-errors
