Update test-kubernetes-master-periodics.yaml

diff --git a/config/jobs/periodic/kubernetes/test-kubernetes-master-periodics.yaml b/config/jobs/periodic/kubernetes/test-kubernetes-master-periodics.yaml
--- a/config/jobs/periodic/kubernetes/test-kubernetes-master-periodics.yaml
+++ b/config/jobs/periodic/kubernetes/test-kubernetes-master-periodics.yaml
@@ -1,81 +1,49 @@
 periodics:
-  - name: periodic-kubernetes-containerd-conformance-test-s390x
+  - name: ci-kubernetes-s390x-conformance-latest-kubetest2
+    interval: 3h
     labels:
-      preset-dind-enabled: "true"
-      preset-ibmcloud-cred: "true"
-    cron: "0 2/3 * * *"
+      preset-ibmcloud-cred-z: "true"
+    decorate: true
+    decoration_config:
+      timeout: 220m
     extra_refs:
-      - base_ref: add-s390x-prov
+      - base_ref: vpc-new
         org: linux-on-ibm-z
-        repo: kubetest2-plugins
+        repo: provider-ibmcloud-test-infra
         workdir: true
-      - base_ref: master
-        org: kubernetes
-        repo: kubernetes
+    annotations:
+      description: Runs conformance tests using kubetest2 against kubernetes ci latest on IBM VPC
     spec:
       containers:
-        - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20241128-8df65c072f-master
+        - image: us-central1-docker.pkg.dev/k8s-staging-test-infra/images/kubekins-e2e:v20251021-e2c2c9806f-master
           securityContext:
             privileged: true
           env:
             - name: "BOSKOS_HOST"
               value: "boskos.test-pods.svc.cluster.local"
+            - name: "USER"
+              value: "ci-kubernetes-s390x-conformance-latest-kubetest2"
           resources:
             requests:
-              memory: "5Gi"
+              cpu: 1
+              memory: "7Gi"
             limits:
-              memory: "5Gi"
+              cpu: 1
+              memory: "7Gi"
           command:
             - runner.sh
           args:
             - bash
             - -c
             - |
-              set -o errexit
-              set -o nounset
-              set -o pipefail
               set -o xtrace
-
               export PATH=$GOPATH/bin:$PATH
               export GO111MODULE=on
-
-              go version
-
-              make install-deployer-tf
-              TF_LATEST="v1.9.8"
-
               RESOURCE_TYPE="vpc-service"
-              USER="periodic-k8s-containerd-conformance-job"
 
-              trap cleanup EXIT
 
-              cleanup(){
-                # stop the boskos heartbeat
-                [[ -z ${HEART_BEAT_PID:-} ]] || kill -9 "${HEART_BEAT_PID}" || true
-              }
-
-              curl -fsSL https://releases.hashicorp.com/terraform/${TF_LATEST:1}/terraform_${TF_LATEST:1}_linux_amd64.zip -o ./terraform.zip
-              unzip -o ./terraform.zip  >/dev/null 2>&1
-              rm -f ./terraform.zip
-              TF="$PWD/terraform"
-              export PATH=$PWD:$PATH
-
-              apt-get update && apt-get install -y ansible
-
-              # Details of IBM S3 storage
-              S3_SERVER=s3.eu-de.cloud-object-storage.appdomain.cloud
-              BUCKET=s390x-ci-builds
-              DIRECTORY=conformance
-
-              # Build and push artifacts to IBM COS
-              REPOROOT=../../kubernetes/kubernetes
-              kubetest2 tf --target-provider vpc --build --target-build-arch linux/s390x --repo-root $REPOROOT --stage cos://eu-de/$BUCKET/$DIRECTORY --cos-cred-type cos_hmac
-              K8S_BUILD_VERSION=`cat $REPOROOT/_output/release-stage/server/linux-s390x/kubernetes/version`
-
-              TIMESTAMP=$(date +%s)
-              jq --arg key0 'k8s-build-version' --arg value0 $K8S_BUILD_VERSION '. | .[$key0]=$value0' <<<'{}' > $ARTIFACTS/metadata.json
-              set +o errexit
-
+              #Call to boskos to checkout resource
+              #source "./hack/boskos.sh"
               heartbeat_account(){
                 count=0
                 url="http://${BOSKOS_HOST}/update?name=${BOSKOS_RESOURCE_NAME}&state=busy&owner=${USER}"
@@ -103,6 +71,7 @@ periodics:
                 elif [[ ${status_code} == 200 ]]; then
                   export BOSKOS_RESOURCE_NAME=$(echo ${output} | jq -r '.name')
                   export BOSKOS_REGION=$(echo ${output} | jq -r '.userdata["region"]')
+                  export BOSKOS_RESOURCE_GROUP=$(echo ${output} | jq -r '.userdata["resource-group-name"]')
                   export BOSKOS_ZONE=$(echo ${output} | jq -r '.userdata["zone"]')
                   rm -rf output.json
                 else
@@ -110,53 +79,59 @@ periodics:
                   exit 1
                 fi
 
+
                 heartbeat_account >> "$ARTIFACTS/boskos.log" 2>&1 &
                 HEART_BEAT_PID=$(echo $!)
               fi
 
-              echo "print variables"
-              echo ${BOSKOS_REGION}
-              echo ${BOSKOS_ZONE}
+              echo "Resource Name:"
               echo ${BOSKOS_RESOURCE_NAME}
+              echo ${BOSKOS_RESOURCE_GROUP}
+              echo ${BOSKOS_ZONE}
 
-              # set -o xtrace
-              kubetest2 tf --target-provider vpc --vpc-node-image-name ibm-ubuntu-22-04-4-minimal-s390x-4 \
-                --vpc-region ${BOSKOS_REGION} --vpc-zone eu-de-1 \
-                --vpc-name ${BOSKOS_RESOURCE_NAME} \
-                --vpc-resource-group rZVPCcloudRG \
-                --vpc-ssh-key k8s-s390x-ssh-key \
-                --vpc-node-profile bz2-4x16 \
-                --ssh-private-key /etc/secret-volume/ssh-privatekey \
-                --s3-server $S3_SERVER --bucket $BUCKET  --directory $DIRECTORY \
-                --extra-vars=k8s_tar_bundles:kubernetes-server-linux-s390x.tar.gz \
-                --extra-vars=pod_subnet:10.244.0.0/16 \
-                --extra-vars=cni_provider:flannel \
-                --build-version $K8S_BUILD_VERSION \
-                --release-marker $K8S_BUILD_VERSION \
-                --cluster-name config1-$TIMESTAMP \
-                --workers-count 2 \
-                --up --auto-approve --retry-on-tf-failure 3 \
-                --break-kubetest-on-upfail true \
-                --test=ginkgo -- --parallel 10 --use-built-binaries true --focus-regex='\[Conformance\]' --skip-regex='\[Serial\]'; rc1=$?
 
-              export KUBECONFIG="$(pwd)/config1-$TIMESTAMP/kubeconfig"
+
+              #Setup of kubetest2 tf deployer and ginkgo tester
+              make install-deployer-tf
+              go install sigs.k8s.io/kubetest2/kubetest2-tester-ginkgo@latest
+
+              CLUSTER_NAME="config1-$(date +%s)"
+
+              set +o errexit
+              set -o xtrace
+              export PATH=$GOPATH/bin:$PATH
+              export GO111MODULE=on
+              RESOURCE_TYPE="vpc-service"
+
+              set +o errexit
+              set -o xtrace
+              kubetest2 tf  --target-provider vpc  --vpc-node-image-name ibm-ubuntu-22-04-4-minimal-s390x-3 \
+              --vpc-region ${BOSKOS_REGION} --vpc-zone ${BOSKOS_ZONE} \
+              --vpc-name ${BOSKOS_RESOURCE_NAME} \
+              --vpc-resource-group ${BOSKOS_RESOURCE_GROUP} \
+              --vpc-ssh-key k8s-s390x-ssh-key \
+              --vpc-node-profile bz2-4x16 \
+              --ssh-private-key /etc/secret-volume/ssh-privatekey \
+              --extra-vars=k8s_tar_bundles:kubernetes-server-linux-s390x.tar.gz \
+              --extra-vars=pod_subnet:10.244.0.0/16 \
+              --extra-vars=cni_provider:flannel \
+              --extra-vars=vpc_api_key:$TF_VAR_vpc_api_key \
+              --build-version $(curl -Ls https://dl.k8s.io/ci/latest.txt) \
+              --cluster-name $CLUSTER_NAME \
+              --workers-count 2 \
+              --up --auto-approve --retry-on-tf-failure 3 \
+              --break-kubetest-on-upfail true \
+              --build-version $(curl -Ls https://dl.k8s.io/ci/latest.txt) \
+              --test=ginkgo -- --parallel 10 --test-package-dir ci --test-package-marker latest.txt --focus-regex='\[Conformance\]' --skip-regex='\[Serial\]'; rc1=$?
+              export KUBECONFIG="$(pwd)/$CLUSTER_NAME/kubeconfig"
               export ARTIFACTS=$ARTIFACTS/serial_tests_artifacts
               #Run Serial Conformance tests
-              kubetest2 tf --target-provider vpc --vpc-region ${BOSKOS_REGION} --vpc-zone eu-de-1 \
+              kubetest2 tf --target-provider vpc --vpc-region ${BOSKOS_REGION} --vpc-zone ${BOSKOS_ZONE} \
                 --ignore-cluster-dir true \
-                --cluster-name config1-$TIMESTAMP \
+                --cluster-name $CLUSTER_NAME \
                 --down --auto-approve --ignore-destroy-errors \
-                --test=ginkgo -- \
-                --use-built-binaries true \
-                --focus-regex='\[Serial\].*\[Conformance\]'; rc2=$?
-              if [ $rc1 != 0 ]; then
-                  echo "ERROR: Non Serial k8s Conformance tests exited with code: $rc1"
-                  exit $rc1
-              elif [ $rc2 != 0 ]; then
-                  echo "ERROR: Serial k8s Conformance tests exited with code: $rc2"
-                  exit $rc2
-              fi
-
+                --test=ginkgo -- --test-package-dir ci \
+                --test-package-marker latest.txt --focus-regex='\[Serial\].*\[Conformance\]'; rc2=$?
               if [ -n "${BOSKOS_HOST:-}" ]; then
                 url="http://${BOSKOS_HOST}/release?name=${BOSKOS_RESOURCE_NAME}&dest=dirty&owner=${USER}"
                 status_code=$(curl -w '%{http_code}' -X POST ${url})
@@ -164,4 +139,12 @@ periodics:
                   echo "Failed to release resource: ${BOSKOS_RESOURCE_NAME}"
                   exit 1
                 fi
+              fi
+
+              if [ $rc1 != 0 ]; then
+                  echo "ERROR: Non Serial k8s Conformance tests exited with code: $rc1"
+                  exit $rc1
+              elif [ $rc2 != 0 ]; then
+                  echo "ERROR: Serial k8s Conformance tests exited with code: $rc2"
+                  exit $rc2
               fi
